version: '3.7'
services:
  creating:
    build: src     
    volumes:
      - type: volume
        source: share
        target: /tmp/war
  
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: 'homework12'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'User123qaz456wsx'
      MYSQL_ROOT_PASSWORD: 'RootMeg@Pa$$w0rd!'
    ports:
      - "3306:33060"

  prod:
    image: tomcat:9.0-jdk11
    volumes:
      - type: volume
        source: share
        target: /usr/local/tomcat/webapps
    ports:
      - "80:8080"
    depends_on:
      - db

volumes:
  share: