version: '3.7'
services:
  creating:
    environment:
      env_file:
        .env
    build: src
    volumes:
      - type: volume
        source: share
        target: /tmp/war
  
  db:
    image: mysql
    environment:
      env_file:
        .env
    healthcheck:
      test: mysqladmin ping -p$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 2m


  prod:
    image: tomcat:9.0-jdk11
    volumes:
      - type: volume
        source: share
        target: /usr/local/tomcat/webapps
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  share: