version: '3.7'
services:
  creating:
    environment:
      - MYSQL_USER=user
      - PORT=3306
      - DBIP=192.168.88.33
      - MYSQL_PASSWORD=User123qaz456wsx
      - MYSQL_DATABASE=homework12
#      env_file:
#        .env
    build: src
    volumes:
      - type: volume
        source: share
        target: /tmp/war
  
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=RootMeg@Pa$$w0rd!
      - MYSQL_DATABASE=homework12
      - MYSQL_USER=user
      - MYSQL_PASSWORD=User123qaz456wsx
#      env_file:
#        .env

  prod:
    image: tomcat:9.0-jdk11
    volumes:
      - type: volume
        source: share
        target: /usr/local/tomcat/webapps
    ports:
      - "80:8080"

volumes:
  share: