version: '3.7'
services:
  creating:
    env_file:
      - conf.env
    build: src
    volumes:
      - type: volume
        source: share
        target: /tmp/war
  
  db:
    image: mysql/mysql-server:latest
    env_file:
      - conf.env
    ports:
      - "3306:33060"

  prod:
    image: tomcat:9.0-jdk11
    volumes:
      - type: volume
        source: share
        target: /usr/local/tomcat/webapps
    ports:
      - "80:8080"
    depends_on:
      - db

volumes:
  share: