version: '3.7'
services:
  creating:
    environment:
      env_file:
        .env
    build: src
    volumes:
      - type: volume
        source: share
        target: /tmp/war
  
  prod:
    image: tomcat:9.0-jdk11
    volumes:
      - type: volume
        source: share
        target: /usr/local/tomcat/webapps

volumes:
  share: